import { NextRequest, NextResponse } from 'next/server';
import { getDatabase } from '../../../../../db';
import { buildBoardSchedule } from '../../../../../dispatch/board-schedule';
import { propose } from '../../../../../matching/propose';
import { planProfileSchema } from '../../../../../shared/contracts/propose';
import type { CandidatePlan, PlanProfile } from '../../../../../shared/types/domain';
import { badRequest, fail } from '../../../_lib/http';

export const dynamic = 'force-dynamic';

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id: eventId } = await params;
  let json: Record<string, unknown> = {};

  try {
    const text = await request.text();
    if (text.trim()) {
      json = JSON.parse(text);
    }
  } catch {
    return badRequest('invalid_json');
  }

  let profile: PlanProfile = 'sla_first';
  if (json.profile) {
    const parsedProfile = planProfileSchema.safeParse(json.profile);
    if (!parsedProfile.success) {
      return badRequest('invalid_profile');
    }
    profile = parsedProfile.data;
  }

  const db = getDatabase();
  const event = await db.events.getById(eventId);
  if (!event) {
    return fail('event_not_found', 404);
  }

  // Live rows, not the snapshot blob. See dispatch/board-schedule.ts.
  const schedule = await buildBoardSchedule(db);

  const proposeOutput = propose({ event, schedule, profile });

  if (proposeOutput.plans.length === 0) {
    await db.events.updateStatus(event.id, 'INFEASIBLE');
    return fail(
      'no_candidate_plans',
      409,
      proposeOutput.message ?? 'propose() returned no plans.',
    );
  }

  const proposal = await db.proposals.create({
    eventId: event.id,
    sourceSnapshotId: schedule.snapshotId,
    // Risk is member 3's classifier. Until it lands, assume the strictest
    // sensible default: every plan stops at the desk rather than auto-committing.
    risk: 'medium',
    autonomyMode: 'approval',
    status: 'RECOMMENDED',
  });

  // propose() marks its own plan for the requested profile RECOMMENDED, but
  // those ids are generated by the engine. candidatePlans.create() assigns the
  // real stored id, so the recommendation must be recorded AFTER saving -
  // otherwise proposal.recommendedPlanId names a row that does not exist, and
  // approving "the recommendation" 404s.
  const savedPlans: CandidatePlan[] = [];
  let recommendedId: string | undefined;

  for (const plan of proposeOutput.plans) {
    const saved = await db.candidatePlans.create({
      proposalId: proposal.id,
      sourceSnapshotId: schedule.snapshotId,
      profile: plan.profile,
      assignments: plan.assignments,
      changeSet: plan.changeSet,
      metrics: plan.metrics,
      validations: plan.validations,
      solverTrace: plan.solverTrace,
      timedOut: plan.timedOut,
      durationMs: plan.durationMs,
      status: plan.status === 'RECOMMENDED' ? 'RECOMMENDED' : 'VALIDATED',
    });
    savedPlans.push(saved);
    if (saved.status === 'RECOMMENDED') {
      recommendedId = saved.id;
    }
  }

  // Fall back to the first saved plan rather than leaving the field dangling.
  recommendedId = recommendedId ?? savedPlans[0]?.id;
  const updated = await db.proposals.updateStatus(proposal.id, 'RECOMMENDED', recommendedId);

  await db.events.updateStatus(event.id, 'PROPOSAL_READY');

  await db.decisionLogs.create({
    eventId: event.id,
    eventType: event.type,
    playbook: 'plan',
    stage: 'propose',
    toolCalls: [],
    summary: `${proposeOutput.engine} produced ${savedPlans.length} plan(s) against snapshot v${schedule.snapshotVersion}; recommended ${recommendedId}.`,
    reasonCodes: [proposeOutput.engine],
    result: 'proposal_ready',
  });

  return NextResponse.json(
    {
      proposal: updated,
      plans: savedPlans,
      engine: proposeOutput.engine,
      timedOut: proposeOutput.timedOut,
    },
    { status: 201 },
  );
}
